# Generated by Django 4.0.6 on 2022-07-10 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Germ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('common_name', models.CharField(max_length=100)),
                ('germ_name', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('mode_of_trans', models.CharField(max_length=100)),
            ],
        ),
    ]
