# Generated by Django 4.0.6 on 2022-07-20 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_symptoms'),
    ]

    operations = [
        migrations.CreateModel(
            name='Symptom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symptom', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Symptoms',
        ),
    ]
