# Generated by Django 4.0.6 on 2022-07-20 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_germ_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='germ',
            name='symptoms',
            field=models.ManyToManyField(to='main_app.symptom'),
        ),
    ]
